// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfU5uNx_n83tAB5XrKJJNb5dDf7CXJ2I4',
    appId: '1:15259939348:web:f8a764b742c03a8f33ad01',
    messagingSenderId: '15259939348',
    projectId: 'datingapp-2703c',
    authDomain: 'datingapp-2703c.firebaseapp.com',
    storageBucket: 'datingapp-2703c.appspot.com',
    measurementId: 'G-M9W4L1HD1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0LvZ_hkC-dsN6yTYBI_3UKjbpZv_4o58',
    appId: '1:15259939348:android:e17978e81366276233ad01',
    messagingSenderId: '15259939348',
    projectId: 'datingapp-2703c',
    storageBucket: 'datingapp-2703c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT_xtTwp9jZCSX-aZDpBO2KpisGxp0Wwc',
    appId: '1:15259939348:ios:1179d92c95279a8233ad01',
    messagingSenderId: '15259939348',
    projectId: 'datingapp-2703c',
    storageBucket: 'datingapp-2703c.appspot.com',
    iosClientId: '15259939348-77sliacn3ocgffq2vr4cku7c539em9pp.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT_xtTwp9jZCSX-aZDpBO2KpisGxp0Wwc',
    appId: '1:15259939348:ios:1179d92c95279a8233ad01',
    messagingSenderId: '15259939348',
    projectId: 'datingapp-2703c',
    storageBucket: 'datingapp-2703c.appspot.com',
    iosClientId: '15259939348-77sliacn3ocgffq2vr4cku7c539em9pp.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );
}
